### ISSUE TITLE
How can I use Inherited Attribute in x3?

### ISSUE THREAD

**Issue by Madokakaroto** [djowel/spirit_x3#15]
If the parser depends on  the attribute of one parser before it, or some globle state, how can I achieve that?

**Comment by djowel** [comment]
Sorry, There are no inherited attributes in X3 yet.

**Comment by Madokakaroto** [comment]
Thanks for reply!
Is there any plan to implement it? Like Qi.

**Comment by djowel** [comment]
Yes there is. Actually there's a way to do it now, but I would not recommend it because it requires injecting a 'context'. This is the same mechanism that will allow inherited attributes in the future.

**Comment by Madokakaroto** [comment]
Thanks, I got it.
