### ISSUE TITLE
Buffered x3::lit

### ISSUE THREAD

**Issue by klemens-morgenstern** [djowel/spirit_x3#16]
Hi Joel,

would it be possible, to add a functionality for x3::lit which buffers the used string? From what I undestand if I write 

``` cpp
std::string value = "Stuff";
auto rule = x3::lit(value);
```

lit only takes a reference to value. So if I do something like this:

``` cpp
auto make_rule() 
{
    std::string str = get_string(); //from somewhere
    return x3::lit(str);
}


auto rule = x3::space >> make_rule();
```

It either will crash while parsing or not parse (I had the latter with msvc).  A nice solution would be a x3::buffered_lit which stores the string inside the rule and is copied - if that is possible.
Now I would add such a feature myself, but I am rather helpless when looking into the spirit code.

I actually solved this issue by providing a buffer for the string, but it would be a nice feature. Might be a corner case though.

My use case is found [here](https://github.com/klemens-morgenstern/Boost.DLL/blob/develop/include/boost/dll/detail/demangling/msvc.hpp#L152)

**Comment by djowel** [comment]
Try x3::string(str) instead

**Comment by klemens-morgenstern** [comment]
Thank you, that worked!
